src/Vaquinha.MVC/Models/ErrorViewModel.cs
using System;

namespace Vaquinha.MVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/Vaquinha.MVC/Controllers/BaseController.cs
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using Vaquinha.Domain;

namespace Vaquinha.MVC.Controllers
{
    public class BaseController : Controller
    {
        private readonly IToastNotification _toastNotification;
        private readonly IDomainNotificationService _domainNotificationService;

        public BaseController(IDomainNotificationService domainNotificationService,
                              IToastNotification toastNotification)
        {
            _domainNotificationService = domainNotificationService;
            _toastNotification = toastNotification;
        }

        protected void AdicionarNotificacaoOperacaoRealizadaComSucesso(string mensagemSucesso = null)
        {
            var sucessMessage = mensagemSucesso ?? "Operação realizada com sucesso!";
            _toastNotification.AddSuccessToastMessage(sucessMessage);
        }

        protected void AdicionarErrosDominio()
        {
            var errorMessage = _domainNotificationService.PossuiErros
                ? _domainNotificationService.RecuperarErrosDominioFormatadoHtml()
                : null;

            if (!string.IsNullOrEmpty(errorMessage))
            {
                _toastNotification.AddErrorToastMessage(errorMessage);
            }
        }
    }
}

src/Vaquinha.MVC/Controllers/DoacoesController.cs
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using System.Threading.Tasks;
using Vaquinha.Domain;
using Vaquinha.Domain.ViewModels;

namespace Vaquinha.MVC.Controllers
{
    public class DoacoesController : BaseController
    {
        private readonly IDoacaoService _doacaoService;
        private readonly IDomainNotificationService _domainNotificationService;

        public DoacoesController(IDoacaoService doacaoService,
                                 IDomainNotificationService domainNotificationService,
                                 IToastNotification toastNotification) : base(domainNotificationService, toastNotification)
        {
            _doacaoService = doacaoService;
            _domainNotificationService = domainNotificationService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(nameof(Index), await _doacaoService.RecuperarDoadoresAsync());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(DoacaoViewModel model)
        {
            _doacaoService.RealizarDoacaoAsync(model);

            if (PossuiErrosDominio())
            {
                AdicionarErrosDominio();
                return View(model);
            }

            AdicionarNotificacaoOperacaoRealizadaComSucesso("Doação realizada com sucesso!<p>Obrigado por apoiar nossa causa :)</p>");
            return RedirectToAction("Index", "Home");
        }

        private bool PossuiErrosDominio()
        {
            return _domainNotificationService.PossuiErros;
        }
    }
}

src/Vaquinha.MVC/Controllers/DoadoresController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Vaquinha.Domain;

namespace Vaquinha.MVC.Controllers
{
    public class DoadoresController : Controller
    {
        private readonly IDoacaoService _doacaoService;

        public DoadoresController(IDoacaoService doacaoService)
        {
            _doacaoService = doacaoService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _doacaoService.RecuperarDoadoresAsync());
        }
    }
}

src/Vaquinha.MVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using NToastNotify;
using System.Threading.Tasks;
using Vaquinha.Domain;

namespace Vaquinha.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly IHomeInfoService _homeService;
        private readonly ILogger<HomeController> _logger;
        private readonly IToastNotification _toastNotification;

        public HomeController(ILogger<HomeController> logger,
                              IHomeInfoService homeService,
                              IToastNotification toastNotification)
        {
            _logger = logger;
            _homeService = homeService;
            _toastNotification = toastNotification;
        }

        public async Task<IActionResult> Index()
        {
            var homeViewModel = await _homeService.RecuperarDadosIniciaisHomeAsync();

            return View(homeViewModel);
        }

        public IActionResult Privacy()
        {
            return View();
        }
    }
}

src/Vaquinha.MVC/Views/Doacoes/Create.cshtml
@model Vaquinha.Domain.ViewModels.DoacaoViewModel

@{
    ViewData["Title"] = "Doar agora";
}


<form asp-action="Create" asp-controller="Doacoes" method="post">

    <div class="text-center">
        <h2>Doe agora</h2>

        <hr />
        <center>
            <div class="col-md-3">
                <div class="form-group">
                    <label asp-for="Valor" class="control-label"></label>
                    <input asp-for="Valor" id="valor" placeholder="Valor doação" class="form-control" />
                </div>
            </div>
            <hr />
        </center>

    </div>

    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-5">

            <fieldset>
                <legend>Dados Pessoais</legend>

                <div class="form-group">
                    <input asp-for="DadosPessoais.Nome" placeholder="Nome Completo" class="form-control" />
                </div>

                <div class="form-group">
                    <input asp-for="DadosPessoais.Email" placeholder="Email" class="form-control" />
                </div>

                <div class="form-group">
                    <textarea asp-for="DadosPessoais.MensagemApoio" class="form-control" rows="3" maxlength="200"
                              placeholder="Deixa aqui uma mensagem de apoio" data-val="true"></textarea>
                </div>

                <div class="form-group float-right">
                    <label asp-for="DadosPessoais.Anonima" class="control-label"></label>
                    <input asp-for="DadosPessoais.Anonima" />
                </div>

            </fieldset>
        </div>
        <div class="col-md-5">

            <fieldset>
                <legend>Endereço de Cobrança</legend>

                <div class="row">
                    <div class="col-md-9">
                        <div class="form-group">
                            <input asp-for="EnderecoCobranca.TextoEndereco" maxlength="100" placeholder="Endereço" class="form-control small" />
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <input asp-for="EnderecoCobranca.Numero" placeholder="Número" class="form-control small" />
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-8">
                        <div class="form-group">
                            <input asp-for="EnderecoCobranca.Cidade" placeholder="Cidade" class="form-control small" />
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <input asp-for="EnderecoCobranca.Estado" placeholder="Estado" id="estado" class="form-control small" />
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-8">
                        <div class="form-group">
                            <input asp-for="EnderecoCobranca.CEP" id="cep" placeholder="CEP" class="form-control small" />
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <input asp-for="EnderecoCobranca.Complemento" placeholder="Complemento" class="form-control small" />
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <input asp-for="EnderecoCobranca.Telefone" id="telefone" placeholder="Telefone" class="form-control small" />
                </div>

            </fieldset>
        </div>
        <div class="col-md-1"></div>
        <div class="col-md-3 text-center"></div>
        <div class="col-md-6 text-center">

            <fieldset>
                <legend>Dados para pagamento</legend>
                <div class="form-group">
                    <input asp-for="FormaPagamento.NomeTitular" placeholder="Nome do Titular" class="form-control" />
                </div>

                <div class="form-group">
                    <input asp-for="FormaPagamento.NumeroCartaoCredito" id="cardNumber" placeholder="Numero do Cartão" class="form-control" />
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <input asp-for="FormaPagamento.Validade" id="validade" placeholder="Data de validade" class="form-control small" />
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <input asp-for="FormaPagamento.CVV" id="cvv" placeholder="CVV" class="form-control small" />
                        </div>
                    </div>
                </div>

            </fieldset>

        </div>
        <div class="col-md-3 text-center"></div>
    </div>


    <div class="text-center">
        <div class="form-group">
            <input type="submit" value="Doar" class="btn btn-yellow" />
        </div>
    </div>

</form>

src/Vaquinha.MVC/Views/Doadores/Index.cshtml
@model IEnumerable<Vaquinha.Domain.ViewModels.DoadorViewModel>
@using System.Globalization
 
@{
    ViewData["Title"] = "Doadores";
}

<div class="text-center">
    <h3>Veja quem já doou!</h3>
    <hr />
</div>


<table class="table table-striped table-bordered text-center">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MensagemApoio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Valor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DescricaoTempo)
            </th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Any())
        {
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MensagemApoio)
                    </td>
                    <td>
                        <span>@item.Valor.ToString("C", CultureInfo.CreateSpecificCulture("pt-BR"))</span>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DescricaoTempo)
                    </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="4">
                    <center> <span class="text-center">Ainda não houveram doações. Seja você o primeiro!</span></center>
                </td>
            </tr>
        }
    </tbody>
</table>

src/Vaquinha.MVC/Views/Home/Index.cshtml
@model Vaquinha.Domain.ViewModels.HomeViewModel
@using System.Globalization 

@{
    ViewData["Title"] = "Vaquinha online";
}

<div class="text-center">
    <h3>Vaquinha online</h3>

    <hr />

    <p>        
        <a asp-controller="Doacoes" asp-action="Create" class="btn btn-yellow">
            <span></span>Doar agora
        </a>
    </p>


    <table class="table table-bordered">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ValorTotalArrecadado)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ValorRestanteMeta)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.QuantidadeDoadores)
                </th>
                <th>
                    <span>Tempo Restante</span>
                </th>
            </tr>
        </thead>
        <tbody>

            <tr>
                <td>
                    @Model.ValorTotalArrecadado.ToString("C", CultureInfo.CreateSpecificCulture("pt-BR"))
                </td>
                <td>
                    @Model.ValorRestanteMeta.ToString("C", CultureInfo.CreateSpecificCulture("pt-BR"))
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model.QuantidadeDoadores)
                </td>
                <td>
                    <code>  @Model.TempoRestanteDias dias - @Model.TempoRestanteHoras horas - @Model.TempoRestanteMinutos minutos</code>
                </td>
            </tr>

        </tbody>
    </table>

    @if (Model.Doadores.Any())
    {
        <hr />

        <h4>Quem já doou?</h4>

        <div id="carouselDoadores" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner" style="background-color: gray;">
                @foreach (var item in Model.Doadores)
                {
                    var active = "";
                    @if (item==Model.Doadores.FirstOrDefault()) {active="active";}
                    <div class="carousel-item @active">
                        <div class="row">
                            <div class="col-2"></div>
                            <div class="col-8">
                                <div class="card">
                                    <div class="card-header">
                                        @item.Nome - @item.Valor.ToString("C", CultureInfo.CreateSpecificCulture("pt-BR"))
                                    </div>
                                    <div class="card-body">
                                        @item.MensagemApoio <br/>
                                        <i>@item.DescricaoTempo</i>
                                    </div>
                                </div>
                            </div>
                            <div class="col-2"></div>
                        </div>
                    </div>
                }
            </div>
            <a class="carousel-control-prev" href="#carouselDoadores" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Próximo</span>
            </a>
            <a class="carousel-control-next" href="#carouselDoadores" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Anterior</span>
            </a>
        </div>
    }

    <hr />

    <h4>Para onde vai minha doação? </h4>

    <div id="carouselInstituicoes" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner" style="background-color: gray;">
            @foreach (var item in Model.Instituicoes)
            {
                var active = "";
                @if (item==Model.Instituicoes.FirstOrDefault()) {active="active";}
                <div class="carousel-item @active">
                    <div class="row">
                        <div class="col"></div>
                        <div class="col">
                            <div class="card">
                                <div class="card-header">
                                    @item.Nome
                                </div>
                                <div class="card-body">
                                    @item.Cidade - @item.Estado
                                </div>
                            </div>
                        </div>
                        <div class="col"></div>
                    </div>
                </div>
            }
        </div>
        <a class="carousel-control-prev" href="#carouselInstituicoes" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Próximo</span>
        </a>
        <a class="carousel-control-next" href="#carouselInstituicoes" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Anterior</span>
        </a>
    </div>



</div>

@section scripts{

    <script type="text/javascript">
        $('#cauroselDoadores').carousel({
            interval: 3000
        });

        $('#cauroselInstituicoes').carousel({
            interval: 2000
        });
        
    </script>
}

src/Vaquinha.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Vaquinha.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-pink border-bottom box-shadow mb-3">
            <div class="container">

                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                                <img src="/images/vaquinha.png" height="50" class="vaquinha-logo"/>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Doadores" asp-action="Index">doadores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Doacoes" asp-action="Create">doar</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2020 - Vaquinha online netcoreapp3.1
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
    @await Component.InvokeAsync("NToastNotify")

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.11/jquery.mask.min.js"></script>

    <script src="~/js/jquery.inputmask.bundle.js"></script>
    <script src="~/js/masks.js"></script>

</body>
</html>